#!/usr/bin/env bash
# test-notif-dismiss-on-open.sh
# Verifies: when user opens a conversation, the related notification is dismissed.
# Test: inject SMS, check notification appears, open chat, verify notification gone.
set -euo pipefail
source "$(dirname "$0")/env.sh"
FAIL=0
pass() { echo "PASS: $1"; }
fail() { echo "FAIL: $1"; FAIL=1; }

info "Inject SMS with OTP"
BODY="probe$RANDOM"
adb_ shell am start -n "$PKG/.MainActivity" >/dev/null 2>&1
sleep 4
adb_ emu sms send +1234567890 "Your code is $BODY" >/dev/null 2>&1
sleep 3

# The app posts one record per conversation, and Android adds a ranker_group
# autogenerated summary on top. Counting every record for the package therefore
# sees other conversations' leftovers, so scope the count to this conversation's
# own id, which is what groupedStyle uses as the notification id.
convo_id() {
  adb_ shell "run-as $PKG sqlite3 databases/messages.db \"SELECT id FROM conversations WHERE address='+1234567890';\"" 2>/dev/null | tr -d '\r\n'
}
# The row only exists once the broadcast has been stored, so wait for it.
for _ in $(seq 1 20); do
  CID=$(convo_id)
  [ -n "$CID" ] && break
  sleep 1
done
if [ -z "${CID:-}" ]; then
  fail "could not resolve the conversation for +1234567890"
fi

count_notifs() {
  adb_ shell "dumpsys notification" 2>/dev/null \
    | grep -cE "NotificationRecord\(.*pkg=$PKG.* id=$CID " || true
}

# Check notification is visible
info "Check notification appeared"
for _ in $(seq 1 20); do
  NOTIF=$(count_notifs)
  [ "$NOTIF" -gt 0 ] && break
  sleep 1
done
if [ "${NOTIF:-0}" -gt 0 ]; then
  pass "notification visible"
else
  fail "notification not found"
fi

# Open the conversation
info "Open conversation"
C=$(center_of_contains "$BODY") || { fail "conversation row not found"; }
[ -n "${C:-}" ] && adb_ shell input tap $C
sleep 3
for _ in 1 2 3; do
  if dump_ui && grep -qE 'class="android.widget.EditText"' "$TMP/ui.xml"; then
    pass "chat screen opened"
    break
  fi
  sleep 1
done

# Check notification is dismissed
info "Check notification dismissed after opening chat"
NOTIF_AFTER=$(count_notifs)
if [ "$NOTIF_AFTER" -eq 0 ]; then
  pass "notification dismissed"
else
  fail "notification still visible (count=$NOTIF_AFTER)"
fi

# Navigate back
adb_ shell "input keyevent 4"
sleep 1

if [ $FAIL -eq 0 ]; then
  echo "== ALL PASSED =="
else
  echo "== SOME FAILED =="
fi
exit $FAIL
